import Foundation

/// Connection settings for the EA (Executive Assistant) backend destination.
///
/// Parallels {@link MySQLConfig}. Both can be enabled simultaneously: a
/// sync pass writes every batch to MySQL (if enabled) AND posts the same
/// batch as JSON to EA's `/api/v1/healthbeat/*` endpoints (if enabled).
///
/// Auth uses a per-integration sync key generated by the EA server
/// (`php artisan ea:healthbeat-key:rotate` — printed once, stored
/// encrypted in `system_credentials.healthbeat_sync_key`). Not the
/// global EA API key.
struct EAConfig: Codable, Equatable {
    var baseURL: String
    var syncKey: String
    var enabled: Bool

    static let `default` = EAConfig(
        baseURL: "https://ea.example.com",
        syncKey: "",
        enabled: false
    )

    private static let userDefaultsKey = "eaConfig_v1"

    static func load() -> EAConfig {
        guard let data = UserDefaults.standard.data(forKey: userDefaultsKey),
              let config = try? JSONDecoder().decode(EAConfig.self, from: data) else {
            return .default
        }
        return config
    }

    func save() {
        if let data = try? JSONEncoder().encode(self) {
            UserDefaults.standard.set(data, forKey: EAConfig.userDefaultsKey)
        }
        Task { @MainActor in iCloudSyncService.shared.pushEAConfig(self) }
    }

    /// Convenience: drops the `?` from URLs that have a trailing query placeholder,
    /// strips trailing slashes — the EAService appends path components itself.
    var normalisedBaseURL: URL? {
        let trimmed = baseURL.trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: "/"))
        return URL(string: trimmed)
    }

    /// Considered configured when the user has both a parseable URL and a key.
    var isConfigured: Bool {
        enabled && normalisedBaseURL != nil && !syncKey.isEmpty
    }
}
